[package]
name = "cgm"
version = "0.1.0"
authors = ["CasualX <CasualX@github.com>"]

description = "Computer Graphics Math Library"

# documentation =
# homepage =
repository = "https://github.com/CasualX/cgmath"

readme = "readme.md"

keywords = ["vector", "matrix"]

license = "MIT"

[features]
default = ["row-major"]

# Use row-major or column-major matrices.
row-major = []
column-major = []

# Invert pitch in euler angles.
invert-pitch = []

# Pretty print radians
format-rad-pi = []
format-rad-tau = []
